apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: kube-state-metrics
    helm:
      values: |
        prometheus:
          monitor:
            enabled: false
          additionalLabels:
            instance: primary
          namespace: "grafana"
          jobLabel: ""
          interval: "60s"
          scrapeTimeout: "120s"
          honorLabels: true
          scheme: https
          tlsConfig: 
            insecureSkipVerify: true
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.20.0
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true
